### ISSUE TITLE
Is this app maintained any longer? 

### ISSUE THREAD

**Issue by algoterranean** [wallabag/ios-app#142]
Is it planned that this application will continue to be maintained? Is the project short of resources, or what is the support plan for 2018? 

I ask because I see several major, application-breaking bugs listed here that have not been fixed in months, one of which I just stumbled across myself after only a few minutes of using the app. 

This is not a criticism, I would just like to know what the plan is so I can decide if I should switch to something else, or some other method of consuming the application on my phone. 

The app is great, btw, when it works. The text-to-speech feature in particular is incredibly useful. :)

**Comment by bourvill** [comment]
hello, it's funny because yesterday i tweet about the wallabag app.

https://twitter.com/bourvill/status/982291476293079040?s=21

yep, it still maintained.

my apologize the current release.

stay tuned, the next release come with lot of fix, stability improvement and some feature like pasteboard url detector.

actually, im the single developer of the app. 
And this is a side project to learn Swift.

i think during this month i can release a new version.

**Comment by algoterranean** [comment]
That is good to hear! Thanks, and keep up the good work!

**Comment by bourvill** [comment]
A beta is rolled out internally. Stay tuned

**Comment by bourvill** [comment]
Release is out, Hope you enjoy it, and fixed your issue.
Thank for your patience.
