### ISSUE TITLE
About the situation

### ISSUE THREAD

**Issue by bourvill** [wallabag/ios-app#168]
Status on the situation

The recent events on the open source repository pushed me to make a choice some time ago,
that of no longer publish on the open source repository but to continue to maintain the application despite everything.

The open source community called for the publication of the missing versions (normal) but I did not want to be bothered in my development with the concerns of "trackings"

So I made the choice to continue to develop my version of the application and to release a new application representing the open source repository.
Unfortunately, Apple has hardened the rules following the latest event on the AppStore, it becomes more difficult, or impossible to have for the same developer two similar applications.

As said in a previous blog post, I believe in usage statistics and they have been instrumental in understanding that one of the important features of the application is the textToSpeech. I do not "steal" any personal information, it does not interest me to know the type of article for example that you read, this information has never been followed.

On my version I made a huge code cleanup, the memory footprint is lower, less bug, a player in podcast mode in preparation to have a perfect companion for reading his articles.
On the open source version, I deleted the code that can be perceived as tracking and delete anything that could prevent the smooth running of the application in time so that it can live a maximum of time without updating.

Also to confirm my choice to have two applications, the choices, and management of wallabag applications is finally done without agreement or choice of the core team, there is no overall vision, common purpose, goal. But we must still be accountable to a community and meet demands that are more constraints than advancement.

The version on the AppStore currently is the non-open source version and it's been like this since months (the problem is not new) and it is, therefore, a delicate situation.

So I decided to release two versions, except that at the time of publication Apple has refused the open source version because too similar to the non-open source version.

I want to publish an open source version to satisfy some.
But I also want to keep my application on the AppStore and make it evolve as I envied.

The update for the current application (non-open source) is ready, it reflects changes to no longer be compared to the open source version. It also fixes the connectivity issues that some are currently experiencing.

So I find myself facing a problem on which today I have no solution to satisfy everyone.

**Comment by j0k3r** [comment]
If I understand the problem is mostly about the tracking, right?
I can truly understand it helps a lot to know what feature are used most than others. So you can spend more time on it improve the app for most users.

I also know that people using open source software tend to not like to be tracked, even if it's only to understand the way people use the app and improve it in that direction instead of something completely useless to everyone.

Instead of trying to solve that complex situation, maybe you should instead allow user to disable tracking. Put a dedicated page in the app about the tracking explaining exactly what information you get, how you are using it and why you are doing so.
Not everyone will disable the feature and I guess, with a good explanation, people will keep the tracking enable.

About Google Analytics, some people see Google as evil, maybe you can try to find a solution with Matomo (ex Piwik). As far as I remember wallabag.it used to have a running instance of Piwik installed, it's disable on app.wallabag.it. But maybe we can provide you an instance so you can track information on it.

About the publication of the code source on GitHub, I like to see what changed between version. That's why I asked about the code few month ago. It's not to see what stuff you are tracking but just to see how you implement some features. Maybe because I'm a developer like you :)

In any case, as part of the wallabag team, we can discuss about those issue on Gitter https://gitter.im/wallabag/wallabag (or the staff channel, as you wish).

**Comment by bourvill** [comment]
It's not because of tracking. It was revealing that people spend time reading code to criticize it, not to help improve it. Yes the criticism can be seen as an improvement, but I did not experience it like that for this case.

We are talking about follow usage, not personal information.

Today, tracking can already be disabled in the settings of the application. Besides, he will no longer use google analytics. (but one of his brothers 😞). I switched to fabric.io, it also helps in error tracking.

As suggested by a user in a private discussion about the app and tracking, would add a page in the registration process to help disabling. With your idea, it would also help to better understand the use.

**Comment by bourvill** [comment]
After several days of reflection, I will redo an attempt to publish and contribute to the project via open source

A lot of change may happen on the repository, I will put my deposit on the one, I will probably have to push force.

I'll incorporate the changes to better inform about the use of the collected information and I will publish my v4, it will integrate a big restructuring of the code, I use now a DI, and will correct some bugs.

Also I would be harder and firm on the issues.

I hope it will be fine, otherwise I will definitely leave the project and I will use my account to publish my version

**Comment by sdeleuze** [comment]
I am not aware of the history of that project, but thanks for making the effort to keep it open-source, I think this is a true differentiator between Wallabag and its competitors. 

If you inform users and let them disable tracking features, I guess that could be fine for most people.
