### ISSUE TITLE
Sharing from Reeder 4 results in flickering overlay

### ISSUE THREAD

**Issue by scribe** [wallabag/ios-app#227]
| Q             | A
| ------------- | ---
| Device?       | iPhone/iPad (Both)
| Device Os version    | 13.2.3
| App Version   | 4.1.3 build 222
| Wallabag server version | 2.3.8

### Steps to reproduce/test case

Open Reeder 4 (4.2.1), select any RSS item from a feed with a long press. Select share, select Wallabag. To clarify this is not from the safari view inside Reeder, this is any other view.

The Wallabag sharing overlay will flicker momentarily, and as far as I can tell neither the app nor the server will have any indication that there was an attempt to send an article.

**Comment by thibaultamartin** [comment]
Hello @scribe 
The Wallabag app is being rewritten. Your issue is mostly fixed in the build 242 of Wallabag 5.0.0 Beta.

If you want to join the beta, you can go to the homepage of this repository and follow the Testflight link. Keep in mind the beta still is unstable, and any update can completely break the app (and potentially do some nasty things on your Wallabag instance).

See issue #231 to follow the status of that issue in beta. This issue will be closed when Wallabag 5.0.0 will be released. Feel free to re-open it if the problem still occurs.
