### ISSUE TITLE
Safari link sharing results in duplicate wallabag entries

### ISSUE THREAD

**Issue by eazy2k13** [wallabag/ios-app#242]
| Q             | A
| ------------- | ---
| Device?       | iPhone
| Device Os version    | 13.3
| App Version   | 4.1.3
| Wallabag server version | 2.3.8

### Steps to reproduce/test case

- Open any URL (e.g. https://en.m.wikipedia.org/wiki/Buzz_Aldrin) in Safari
- Click on the share icon on the bottom
- Select wallabag
- The site gets added twice to wallabag

**Comment by thibaultamartin** [comment]
The Wallabag app is being rewritten. Your issue is most likely fixed in the build 242 of Wallabag 5.0.0 Beta.

If you want to join the beta, you can [follow the Testflight link](https://testflight.apple.com/join/RF9hzKHt). Keep in mind the beta still is unstable, and any update can completely break the app (and potentially do some nasty things on your Wallabag instance).

This issue will be closed when Wallabag 5.0.0 will be released. Feel free to re-open it if the problem still occurs.
