### ISSUE TITLE
Tags

### ISSUE THREAD

**Issue by grizzee** [wallabag/ios-app#26]
Access to the Tags from the Webversion. Tags are important to sort items in topics or other context.

**Comment by bourvill** [comment]
what did you expect from tag? Can you tell an user story ?

I think is big subject, we can produce small step on each release

**Comment by j0k3r** [comment]
I think you can do that (maybe in a different release for each step):
- display tag below article title (maybe not in the list view, only in the article view)
- ability to clic on that tag to list all articles for it
- ability to filter article in the tag view (by unread, starred, etc.)

**Comment by grizzee** [comment]
I want to use tags to sort articles and links. 
For example: #Receipts i found, things around the topic #cycling. Or i collect all links to interesting Audios and Podcasts under the tag #listenlater. Articles wich have no tag are in the "inbox" and can sort from there under topics and contexts. Articles wich stay in the inbox could be the current reading list. In this way i use pocket at the moment but looking forward to the iOS-App and wallabag.it
I agree with the ideas from @j0k3r 

>- display tag below article title (maybe not in the list view, only in the article view)
>- ability to clic on that tag to list all articles for it
>- ability to filter article in the tag view (by unread, starred, etc.)

**Comment by gerhard-tinned** [comment]
I am missing the tags in the iOS app too. The proposal from @j0k3r sounds very good. 

Also the use-case from @grizzee sounds very similar to mine. :-)

**Comment by bourvill** [comment]
This is a big thread, we introduce small work tag for each next release

With the upcoming release 2.2, we introduce a first step of tag feature in the app.

You can find your tag on article and work with them.
Maybe we introduce a new menu "tag" list all tag and find article releated to this one

It's big work in order to provide a powerfull and usefull feature

Stay tunned

**Comment by gerhard-tinned** [comment]
Thanks for the update. 

I really like the iOS app really a lot. Thanks for the great work! I understand there is the need to take it in small steps. 

I am very excited to see the next version and its new features. -- Keep up the great work!!

**Comment by mayaahh** [comment]
I would love to be able to set tags within the prompting widget at the moment when I add something (typically a news from a dedicated app as Le Monde) to my wallabag. Existing tags should be suggested, exactly as in Pocket. 
Thanks!

**Comment by thibaultamartin** [comment]
The Wallabag app is being rewritten. Your issue is most likely fixed in the build 242 of Wallabag 5.0.0 Beta.

If you want to join the beta, you can [follow the Testflight link](https://testflight.apple.com/join/RF9hzKHt). Keep in mind the beta still is unstable, and any update can completely break the app (and potentially do some nasty things on your Wallabag instance).

This issue will be closed when Wallabag 5.0.0 will be released. Feel free to re-open it if the problem still occurs.
