### ISSUE TITLE
iOS shortcut to add a entry

### ISSUE THREAD

**Issue by andrewchenshx** [wallabag/ios-app#295]
How can I use iOS shortcut to quickly add a entry to wallabag?

**Comment by bourvill** [comment]
Hello,
When you say shortcut, do you mean long press on the logo home page? because the addition from this means is not planned.

On the other hand if you want to talk about the share extension, you just need to navigate with your browser and press the share button. On this page you may need to activate wallabag. Then if your app is properly configured, the site will be added to your wallabag instance. (in the application a synchronization must be carried out for the moment)

There is a correction in progress on the extension to take into account PDF urls for example.

**Comment by andrewchenshx** [comment]
hi, my fault.
I mean the “shortcuts” app, which is
 formerly known as “Workflow “.

**Comment by bourvill** [comment]
super interesting!

It is not planned at the moment, but it remains possible.

I transform your request into a Feature request

**Comment by HenryQW** [comment]
Here you go, a simple one. Adds an entry with a link from the sharesheet.

https://www.icloud.com/shortcuts/279ec18519f44d61babea6416dddd5db

**Comment by bourvill** [comment]
@HenryQW Nice workaround.

--- 
The goal of this feature will ultimately be to have wallabag as a termination choice for shortcut

**Comment by bourvill** [comment]
![Capture d’écran 2020-07-01 à 23 47 30](https://user-images.githubusercontent.com/295272/86294648-45c2d700-bbf5-11ea-870c-1f6d72a4368a.png)

trying to make this happen :)

**Comment by bourvill** [comment]
@andrewchenshx beta build is submitted, waiting for beta approval in TestFlight

**Comment by bourvill** [comment]
@andrewchenshx Have you tested beta?

**Comment by andrewchenshx** [comment]
> @andrewchenshx Have you tested beta?

it works as expected. Thanks

**Comment by huseyz** [comment]
@bourvill am I right assuming this never made it to the release?

**Comment by bourvill** [comment]
it's a bug. this feature was developed but no longer seems to appear. I will investigate and suggest a fix.

**Comment by bourvill** [comment]
Fix in 7.0.3
