### ISSUE TITLE
Offline mode

### ISSUE THREAD

**Issue by bourvill** [wallabag/ios-app#5]
Store article localy

**Comment by nielsk** [comment]
Please add this. I am searching an alternative to Instapaper or Pocket (and wallabag seems to want to be position itself to this) and those sites started to exist because the mobile net was slow. And you want to be able to read your articles while offline or when coverage is crappy. I was really surprised today when I installed the app and it didn't work in the subway where the mobile network is really slow.

**Comment by goodworkguy** [comment]
This is the missing feature for me. I thought offline reading was the purpose, but the app doesn't load if you're not online. I'll be back when this feature is in!

**Comment by bourvill** [comment]
I work on it ;)

**Comment by bourvill** [comment]
this change will be available in next release
