### ISSUE TITLE
Login error when server redirect to https

### ISSUE THREAD

**Issue by j0k3r** [wallabag/ios-app#56]
I've defined `http://app.wallabag.it` as the server and when submitting my login / password, the popup of login error raised.
I've tried several time with the right login / password and still got the error.

When changing the server to `https://app.wallabag.it` I succeed in logged in.

Maybe the 301 redirect generate a login error?

**Comment by bourvill** [comment]
:+1: for the redirect i think

**Comment by khinsen** [comment]
I get a login error even when I do use https explicitly. OK, my situation is not quite the same. There is no redirect, because Apache on my server doesn't even listen to port 80. But all logins fail. Yes, I did check all the data several times, and everything was copied/pasted from the Web app anyway.

**Comment by thibaultamartin** [comment]
The Wallabag app is being rewritten. Your issue is most likely fixed in the build 242 of Wallabag 5.0.0 Beta.

If you want to join the beta, you can [follow the Testflight link](https://testflight.apple.com/join/RF9hzKHt). Keep in mind the beta still is unstable, and any update can completely break the app (and potentially do some nasty things on your Wallabag instance).

This issue will be closed when Wallabag 5.0.0 will be released. Feel free to re-open it if the problem still occurs.
