### ISSUE TITLE
When I change state of an article, return to the list

### ISSUE THREAD

**Issue by j0k3r** [wallabag/ios-app#9]
When I change state of an article (as read or as unread), return to the list and remove that article from the current list.
But I think it can't apply to starred / unstarred. I don't know.

**Comment by bourvill** [comment]
actually it's hardest to remove article from list. i'm explain this:

When mark article  read or unread, the article is updated in list wich opened, but it's don't match the list with the current selected filter:  starred, readed.... Clearly it's bug...

We need to rework the list with expected behavior.

I create a new issue with this part, and work only with return to list with this one
